# Taken from https://github.com/xbernpa/fluentd-kubernetes-gelf/blob/master/kubernetes/fluentd-daemonset-gelf.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: opus-prod
  namespace: kube-system
  labels:
    k8s-app: fluentd-gelf-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluentd-gelf-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      nodeSelector:
        kubernetes.io/role: node
      containers:
      - name: fluentd
        image: xbernpa/fluentd-kubernetes-gelf
        env:
          - name: GELF_HOST
            value: "1.2.3.4"
          - name: GELF_PORT
            value: "12201"
          - name: GELF_PROTOCOL
            value: "udp"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers